#title: item 전체 조회
GET {{baseUrl}}/items

################################################################

#title: item 전체 조회(개선)
GET {{baseUrl}}/items/v2

################################################################

#title: item 전체 조회(개선)
GET {{baseUrl}}/items/v3

################################################################

#title: item 상세 조회
GET {{baseUrl}}/items/1

################################################################
#title: item 삭제(비활성화)
DELETE {{baseUrl}}/admins/items/100
