version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources:/app/config
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: shop
    volumes:
      - ./db/mysql-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - .db/redis_data:/data
    environment:
      - REDIS_PASSWORD=test123
      - REDIS_DATABASE=0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge