spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
#        format_sql: true
#        use_sql_comments: true
#        show_sql: true
#        session:
#          events:
#            log:
#              LOG_QUERIES_SLOWER_THAN_MS: 1
#        stats:
#          factory: com.example.yoonnsshop.config.CustomStatisticsImpl
#        session_factory:
#        statement_inspector: com.example.yoonnsshop.aop.CustomStatementInspector
#    open-in-view: true

  data:
    redis:
      port: 6379
      host: localhost
      password: test123
      database: 0

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.type: trace
#    org.hibernate.stat: debug
#    com.example.yoonnsshop: DEBUG
#    com.example.yoonnsshop.aop: DEBUG
#    org.hibernate: DEBUG