spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: shop
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: http://localhost:8080/api/v1/oauth/code/google
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  datasource:
    hikari:
      maximum-pool-size: 10

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
#        orm:
#          jdbc:
#            bind: TRACE
    com:
      example:
        yoonnsshop: DEBUG

jwt:
  jwtsecret: ${JWT_SECRET}
  jwtExpirationTime: 86400000

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    enable:
      hikaricp: true