spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
  data:
    redis:
      port: 6379
      host: localhost
      password: test123
      database: 0

# ?? ??? ???
#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#        stat: DEBUG
#    com:
#      example:
#        yoonnsshop: DEBUG