# insert test data
# admin
INSERT INTO ADMINS (EMAIL, PASSWD) VALUES ('test@test.com', '$2y$10$HIAHCALHoK.ocMRW6EK7IOq6EOA0WxJmMDfNrffNrxZUEx8YEq/4u');

# item
INSERT INTO ITEMS (ITEM_DESCRIPTION, ITEM_NAME, ITEM_PRICE, ITEM_STOCK_QUANTITY) VALUES ('아이템', 'item1', 100.00, 200);
